services:
  brain-api:
    build: 
      context: .
      dockerfile: brain-api/Dockerfile
      args:
        - CACHE_BUST=1
    restart: always
    environment:
      - WEAVIATE_URL=http://weaviate:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.brain-api.rule=Host(`api.brain.kluth.cloud`)
      - traefik.http.routers.brain-api.entrypoints=websecure
      - traefik.http.routers.brain-api.tls.certresolver=letsencrypt
      - traefik.docker.network=ai-network
    networks:
      - ai-network

networks:
  ai-network:
    external: true
